#!/bin/bash
echo "=== Checking sidepanel build status ==="
echo ""
echo "1. Sidepanel HTML exists:"
ls -lh src/panel/sidepanel.html 2>/dev/null && echo "✓ HTML found" || echo "✗ HTML missing"
echo ""
echo "2. Sidepanel JS source exists:"
ls -lh src/panel/sidepanel.js.arch 2>/dev/null && echo "✓ Source found" || echo "✗ Source missing"
echo ""
echo "3. Built sidepanel JS exists:"
ls -lh dist/panel/sidepanel.js 2>/dev/null && echo "✓ Built JS found" || echo "✗ Built JS missing"
echo ""
echo "4. Built sidepanel JS size:"
wc -c dist/panel/sidepanel.js 2>/dev/null | awk '{print $1 " bytes"}'
echo ""
echo "5. Checking if built JS contains initialization code:"
grep -q "DOMContentLoaded" dist/panel/sidepanel.js 2>/dev/null && echo "✓ DOMContentLoaded listener found" || echo "✗ DOMContentLoaded listener missing"
echo ""
echo "6. Checking if built JS contains SidepanelController:"
grep -q "initialize" dist/panel/sidepanel.js 2>/dev/null && echo "✓ initialize method found" || echo "✗ initialize method missing"
echo ""
echo "7. Manifest includes sidepanel:"
grep -A5 "side_panel" manifest.json 2>/dev/null || echo "✗ No sidepanel config in manifest"
