(function(g){var e=window.AmazonUIPageJS||window.P,m=e._namespace||e.attributeErrors,f=m?m("CSHelpSearchAutocompleteJS",""):e;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,e,m){g.when("jQuery").register("cs-retail-help-autocomplete",function(f){Function.prototype._bind=function(c){var e=this;return function(){for(var f=[this],g=0,d=arguments.length;g<d;g++)f.push(arguments[g]);return e.apply(c,f)}};g.when("A","ready").register("llm-search-box",function(c){c.declarative("clear_search",
"click",function(e){c.$("#helpsearch").val("");c.$("#clear-button").addClass("a-hidden")});c.$("#helpsearch").bind("input",function(){""!==c.$("#helpsearch").val()?c.$("#clear-button").removeClass("a-hidden"):c.$("#clear-button").addClass("a-hidden")})});return{searchSuggest:function(c,g,x,y){this.searchFormName=c.attr("id");this.formElement=c.get(0);this.searchBox=c.find("#"+g).get(0);this.hiddenInput=c.find("#"+x).get(0);this.submitButton=c.find("#"+y).get(0);var d=-1,n=[],h=0,k="",p=null,q=null,
r=null,t=!1,v=!1,u=c.find("#help_srch_sggst").get(0),w=c.find('[name\x3d"locale"]').val();this.init=function(){v||(t=-1!==navigator.userAgent.toLowerCase().indexOf("msie"),this.searchBox&&(k=this.searchBox.value,this.searchBox.setAttribute("autocomplete","off"),this.attachEventListener(this.searchBox,"keydown",this.onKeyDownEvent),this.attachEventListener(this.searchBox,"keyup",this.onKeyUpEvent),this.attachEventListener(this.searchBox,"keypress",this.onKeyPressedEvent),this.attachEventListener(this.searchBox,
"blur",this.onFocusLost),r=e.onresize,this.attachEventListener(e,"resize",this.onWindowResized),v=!0))};this.onKeyDownEvent=function(a,b){switch(b.keyCode){case 40:this.moveDown();this.stopEvent(b);break;case 38:this.moveUp(),this.stopEvent(b)}}._bind(this);this.onKeyUpEvent=function(a,b){switch(b.keyCode){case 13:this.HideSuggestionsDiv();break;case 40:break;case 38:break;case 37:break;case 39:break;default:a=this.searchBox.value,a!==k&&(k=a,this.setSearchSuggestionTimeout())}}._bind(this);this.onKeyPressedEvent=
function(a){if(27===a.keyCode&&"none"!==this.getSearchSuggest().style.display)return this.setSuggestionHideTimeout(),this.searchBox.value=k,!1}._bind(this);this.onFocusLost=function(a){this.setSuggestionHideTimeout()}._bind(this);this.onWindowResized=function(a){this.getSearchSuggest().style.width=this.searchBox.offsetWidth;r&&r(a)}._bind(this);this.moveDown=function(){if(!(0>=h))try{this.unhighlightCurrentSuggestion(),d>=h-1?d=-1:++d,this.highlightCurrentSuggestion(!0)}catch(a){}};this.moveUp=function(){if(!(0>=
h))try{this.unhighlightCurrentSuggestion(),0>d?d=h-1:--d,this.highlightCurrentSuggestion(!0)}catch(a){}};this.stopEvent=function(a){t?a.cancelBubble=!0:a.preventDefault()};this.displaySuggestions=function(){try{h=Math.min(7,n.length)}catch(d){h=0}var a=this.getSearchSuggest();f(a).width(f(this.searchBox).parent().width());a.style.position="absolute";a.style.zIndex="130";a.innerHTML="";0<h?a.style.display="":this.HideSuggestionsDiv();for(var b,l=0;l<h;++l)b="issDiv"+l,b='\x3cdiv id\x3d"'+b+'"',b+=
'class\x3d"suggest_link"\x3e'+this.getFormattedSuggestionLine(n[l])+"\x3c/div\x3e",a.innerHTML+=b;0<h&&(a.innerHTML+='\x3cdiv id\x3d"issdivhdr" align\x3d"right"\x3e\x26nbsp;\x3c/div\x3e');for(l=0;l<h;++l)b="issDiv"+l,this.attachEventListener(c.find("#"+b).get(0),"mouseover",this.suggestOver),this.attachEventListener(c.find("#"+b).get(0),"mouseout",this.suggestOut),this.attachEventListener(c.find("#"+b).get(0),"click",this.setSearchByIndex)};this.setSearchByIndex=function(a){d=(a.id?a:e.event.srcElement).id.substr(6);
this.highlightCurrentSuggestion(!0);this.getSearchSuggest().innerHTML="";this.formElement.submit()}._bind(this);this.suggestOver=function(a,b){a.style||(a=e.event.srcElement?e.event.srcElement:e.event.originalTarget);a.style.cursor="default";this.unhighlightCurrentSuggestion();d=a.id.substr(6);this.highlightCurrentSuggestion(!1)}._bind(this);this.suggestOut=function(a,b){a.style||(a=e.event.srcElement?e.event.srcElement:e.event.originalTarget);this.unhighlightSuggestion(a)}._bind(this);this.highlightSuggestion=
function(a){a.className="suggest_link_over"};this.unhighlightSuggestion=function(a){a.className="suggest_link"};this.highlightCurrentSuggestion=function(a){if(a)if(-1===d)this.searchBox.value=k;else{a=n[d];if(!a)return;this.hiddenInput.value=[k,a,d].join();this.searchBox.value=a}a=c.find("#issDiv"+d).get(0);this.highlightSuggestion(a)};this.unhighlightCurrentSuggestion=function(){var a=null;try{a=c.find("#issDiv"+d).get(0)}catch(b){}a&&this.unhighlightSuggestion(a)};this.getFormattedSuggestionLine=
function(a){var b=k.toLowerCase().split(" ");a=a.toLowerCase().split(" ");return f.map(a,function(a,c){return-1!==f.inArray(a,b)?"\x3cb\x3e"+a+"\x3c/b\x3e":a}).join(" ")};this.setSuggestionHideTimeout=function(){setTimeout(function(){return function(){this.HideSuggestionsDiv()}}()._bind(this),300)};this.setSearchSuggestionTimeout=function(){n=[];this.hiddenInput.value="";p&&(clearTimeout(p),p=null);q&&(q.abort(),q=null);var a=w.split("_")[0];k.length<("zh"===a||"jp"===a?1:3)?this.HideSuggestionsDiv():
p=setTimeout(function(){p=null;var a=k.toLowerCase();q=f.getJSON("/gp/help/customer/ajax/autocomplete.html",{locale:w,userQuery:a,ie:"UTF8"}).done(function(a,b){q=null;n=b;this.displaySuggestions();d=-1}._bind(this))}._bind(this),100)};this.HideSuggestionsDiv=function(){h=0;this.getSearchSuggest().innerHTML="";this.getSearchSuggest().style.display="none";d=-1};this.findPos=function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;while(a)}return[b,c]};this.createSuggestionDiv=
function(a){var b=c.find("#helpsearch").get(0);b.offset();b.height();b=document.createElement("div");b.style.border="1px solid #5c8295";b.style.backgroundColor="white";b.style.color="black";b.style.width=a.offsetWidth;b.style.zIndex="130";b.style.display="none";b.id="help_srch_sggst";a=a.parentNode;b.style.position="absolute";t&&(a=a.parentNode);a.appendChild(b);return b};this.getSearchSuggest=function(){u||(u=this.createSuggestionDiv(this.searchBox));return u};this.attachEventListener=function(a,
b,c){var d="on"+b;if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent(d,c);else{var e=a[d];a[d]=function(){var a=e.apply(this,arguments),b=c.apply(this,arguments);return a===m?b:b===m?a:b&&a}}}}}})});